spring:
#  profiles:
#    active: dev
  messages:
    basename: messages, errors
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: validate
#      ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#        show_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
  ssl:
    key-store: classpath:springKey1
    key-store-type: PKCS12
    key-store-password: 123123
    key-alias: springKeyStore

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace
